"""update

Revision ID: 2f106d7fd125
Revises: 64df2c517841
Create Date: 2024-12-08 11:02:42.150873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f106d7fd125'
down_revision = '64df2c517841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('url_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('createtime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updatetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('visitor_num', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('nikname')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=11), nullable=True))
        batch_op.add_column(sa.Column('nikname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('visitor_num')
        batch_op.drop_column('updatetime')
        batch_op.drop_column('createtime')
        batch_op.drop_column('password')
        batch_op.drop_column('url_key')
        batch_op.drop_column('url')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
