"""empty message

Revision ID: 64df2c517841
Revises: 
Create Date: 2024-12-08 10:36:02.698542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64df2c517841'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nikname', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('nikname')

    # ### end Alembic commands ###
